# Generated by Django 5.2.4 on 2026-07-28 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0007_barbershop_applicant_type_certificate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_e164', models.CharField(db_index=True, max_length=16)),
                ('code', models.CharField(max_length=6)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'קוד כניסה',
                'verbose_name_plural': 'קודי כניסה',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50, verbose_name='שם תצוגה')),
                ('phone_e164', models.CharField(max_length=16, unique=True, verbose_name='טלפון')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='תמונת פרופיל')),
                ('bio', models.CharField(blank=True, default='', max_length=300, verbose_name='על עצמי')),
                ('onboarded', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='member', to='catalog.barbershop', verbose_name='מועמדות')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'חבר/ה',
                'verbose_name_plural': 'חברי קהילה',
            },
        ),
    ]
