# Generated by Django 5.2.4 on 2026-07-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_barbershop_sector_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='אימייל'),
        ),
    ]
