# Generated by Django 5.2.4 on 2026-07-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_barbershop_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='occupation',
            field=models.CharField(choices=[('hair', 'מעצב/ת שיער'), ('barber', 'ברבר'), ('makeup', 'מאפר/ת'), ('cosmetics', 'קוסמטיקאי/ת'), ('nails', 'מעצב/ת ציפורניים'), ('other', 'אחר')], default='other', max_length=20, verbose_name='תחום עיסוק'),
        ),
        migrations.AlterField(
            model_name='barbershop',
            name='business_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='שם העסק'),
        ),
        migrations.AlterField(
            model_name='barbershop',
            name='owner_name',
            field=models.CharField(max_length=120, verbose_name='שם מלא'),
        ),
    ]
