# Generated by Django 5.2.4 on 2026-07-28 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at', '-pk'], 'verbose_name': 'פוסט', 'verbose_name_plural': 'פוסטים'},
        ),
    ]
